### ISSUE TITLE
Hardcoded repo for patterns-suma_server package broke MU and is not needed

### ISSUE THREAD

**Issue by ktsamis** [moio/sumaform#369]
In the file ```sumaform/salt/suse_manager_server/init.sls```
we have this:

```
suse_manager_packages:
  pkg.latest:
    {% if 'head' in grains['version'] or 'test' in grains['version'] %}
    - fromrepo: Devel_Galaxy_Manager_Head
    {% elif '3.0-released' in grains['version'] %}
    - fromrepo: SUSE-Manager-3.0-x86_64-Pool
    {% elif '3.0-nightly' in grains['version'] %}
    - fromrepo: Devel_Galaxy_Manager_3.0
    {% elif '3.1-released' in grains['version'] %}
    - fromrepo: SUSE-Manager-3.1-x86_64-Pool
    {% elif '3.1-nightly' in grains['version'] %}
    - fromrepo: Devel_Galaxy_Manager_3.1
    {% elif '3.2-released' in grains['version'] %}
    - fromrepo: SUSE-Manager-3.2-x86_64-Pool
    {% elif '3.2-nightly' in grains['version'] %}
    - fromrepo: Devel_Galaxy_Manager_3.2
     {% endif %}
    - name: patterns-suma_server
    - require:
      - sls: suse_manager_server.repos
      - sls: suse_manager_server.firewall
```

since the module is pkg.latest and the repos are set correctly in ```sumaform/salt/suse_manager_server/repos.sls``` the check for the grain is not needed. It's already checked when the repos are set and if we hardcode the repos where the package is coming from, then if I add ```additional_repos``` that contain this package (as was the MU I was doing) then it's not updated, its dependencies are not updated/installed and the server is not properly set up.

@moio can you assign this to me? I will open a PR when I test this and it doesn't break anything.

**Comment by mcalmer** [comment]
@ktsamis AFAIK it has a reason to pick "from" a specific channel. We have setup channels which are not really part of a typical SUSE Manager Setup which might provide some of these packages in newer versions. AFAIK this prevent to install to choose them. But @moio has a better overview about this.

**Comment by ktsamis** [comment]
@mcalmer The only package that is "hardcoded" is the patterns-suma_server and it should be able to install from whichever repo is available. You can still add whatever channels you want in ```sumaform/salt/suse_manager_server/repos.sls``` and in ```additional_repos```. It's just that this package will be able to install from those as well instead of only the hardcoded ones. The version of the pattern package will always be higher, whenever we rebuilt it so it should be always be updated with the pkg.latest. 

I don't see a reason to install an older pattern package but let's see what @moio thinks. If there is a reason, sure let's leave it but I just don't see it now :smiley:

**Comment by moio** [comment]
@mcalmer what happens when we have `Devel:` repos? Are we sure the pattern version is always higher there?

If we are, this might simply be something that got carried over since the 2.1 times, when we did not have the pattern and this was needed in order to get the right package selection.

In that case, I am OK for @ktsamis to take care of this provided that at least 3.1-stable, 3.1-nightly and heat are tested manually after the patch (deployment of a SUSE Manager Server in isolation and check of package versions).

**Comment by mcalmer** [comment]
Since some time now we manipulate the "release" number of RPM packages build in our Devel Projects.
We add as the first number a representation of the version.

E.g. in
- Devel:Galaxy:Manager:3.1 we use 310.<CI_CNT>.<B_CNT>.devel31
- Devel:Galaxy:Manager:3.2 we use 321.<CI_CNT>.<B_CNT>.devel32

Client Tools are based on some major version (we just switched to 3.2)
- Devel:Galaxy:Manager:3.2:SLE12-SUSE-Manager-Tools we use 320.<CI_CNT>.<B_CNT>.devel32

NOTE: 321 vs. 320

Client Tools are lower then "main". I did this to solve some problems with sumaform and update of the salt package. If Client Tools salt minion is installed and a master must be installed we now have always and `update to a higher version` and **not** a `downgrade`.

**Comment by ktsamis** [comment]
@mcalmer I don't understand what you mean with the rpm numbers, kinda got lost in the explanation. Why do the client tools matter when I am just setting up the server? Client tools should not be installed in the server, no? I know salt-minion is setup in all sumaform servers but not sure how this is related.


What I can confirm at the moment removing all the checks and having ```sumaform/salt/suse_manager_server/init.sls``` like this:

```
 suse_manager_packages:
   pkg.latest:
-    {% if 'head' in grains['version'] or 'test' in grains['version'] %}
-    - fromrepo: Devel_Galaxy_Manager_Head
-    {% elif '3.0-released' in grains['version'] %}
-    - fromrepo: SUSE-Manager-3.0-x86_64-Pool
-    {% elif '3.0-nightly' in grains['version'] %}
-    - fromrepo: Devel_Galaxy_Manager_3.0
-    {% elif '3.1-released' in grains['version'] %}
-    - fromrepo: SUSE-Manager-3.1-x86_64-Pool
-    {% elif '3.1-nightly' in grains['version'] %}
-    - fromrepo: Devel_Galaxy_Manager_3.1
-    {% elif '3.2-released' in grains['version'] %}
-    - fromrepo: SUSE-Manager-3.2-x86_64-Pool
-    {% elif '3.2-nightly' in grains['version'] %}
-    - fromrepo: Devel_Galaxy_Manager_3.2
-     {% endif %}
     - name: patterns-suma_server
     - require:
       - sls: suse_manager_server.repos
```
breaks the server setup, a lot of states fail, the package is not installed, or the salt-master package (one of the other states that depend on this one). 

So completely removing this, breaks the server setup, adding additional repos that contain the pattern package also breaks the server setup in the same way. For sure I will not remove the checks since it breaks head, 3.1-released, 3.1-nightly. Those were the ones I checked so far, I assume it is the same with 3.0 and maybe 3.2.

**Comment by ktsamis** [comment]
Also since we released the MU for both 3.0 and 3.1, the server setup started failing for my production jenkins jobs. The 3.1 was already broken during the MU, now the 3.0 also fails.

**Comment by mcalmer** [comment]
AFAIK sumaform add the client tools channel. @moio might remember why this was needed.

**Comment by moio** [comment]
1) sumaform uses Salt for deployment
 1) as per the design, the Salt version available in base sumaform images is not known a priori, and typically is very old
 1) Manager includes Salt as a component, and needs it at a very specific version
 1) 1 and 2 and 3 implies that we have to upgrade Salt as part of a Manager sumaform deployment, in order to match the version needed by Manager
 1) upgrading Salt with Salt is notoriously fragile - the `state.apply` call will fail with error in most old/new version combinations despite the package being correctly updated. Recommendation from upstream: do a separate Salt call that only upgrades Salt with Salt
 1) sumaform respects 5, but that separate call must also deal with setting the repos to get the correct version from, plus a very few other essential operations. Anything in this call is very delicate as we ignore errors (we can't do otherwise because 5)
 1) following 6 we try to keep this phase as minimal as possible. The correct Salt version for a certain SUSE Manager version is either in the Server repo itself or in its corresponding Tools repo, because those are in sync by design. The latter contains a much smaller number of packages and also makes more sense code-wise (see the salt/default/ directory), that's why the Tools repo is used

**Comment by moio** [comment]
I think your Jenkins job is pulling from the wrong branch, as I still see this line:

> module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ] Running state [patterns-suma_server] at time 11:16:27.920317
> module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ] Executing state pkg.latest for [patterns-suma_server]
> module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ] Executing command [u'zypper', u'--non-interactive', u'--no-refresh', u'info', u'-t', u'package', u'patterns-suma_server'] in directory '/root'
> module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ] **Targeting repo 'SUSE-Manager-3.1-x86_64-Pool'**
> module.srv.module.suse_manager.libvirt_domain.domain (remote-exec): [INFO    ] Executing command [u'zypper', u'--non-interactive', u'--no-refresh', u'--no-refresh', u'install', u'--auto-agree-with-licenses', u'--name', u'--force', u'--force-resolution', u'--from', u'SUSE-Manager-3.1-x86_64-Pool', u'patterns-suma_server'] in directory '/root'


Looking at a healthy PTS run:

> module.pts.module.server.module.suse_manager.null_resource.host_salt_configuration (remote-exec): [INFO    ] Running state [patterns-suma_server] at time 10:00:39.820505
> module.pts.module.server.module.suse_manager.null_resource.host_salt_configuration (remote-exec): [INFO    ] Executing state pkg.latest for [patterns-suma_server]
> module.pts.module.server.module.suse_manager.null_resource.host_salt_configuration (remote-exec): [INFO    ] Executing command [u'zypper', u'--non-interactive', u'--no-refresh', u'info', u'-t', u'package', u'patterns-suma_server'] in directory '/root'


"**Targeting repo 'SUSE-Manager-3.1-x86_64-Pool'**" does not show up

**Comment by ktsamis** [comment]
This was an old run, I had disabled the testsuite. Now it works for 3.1 again, thanks @moio
