### ISSUE TITLE
Allow bridged networks

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#78]
Currently, the documented way to do a bridged setup is to do

    network_name=""
    bridge = "br0"

For one, it's not a very natural syntax (the magic empty string must be there), but that's not the issue I want to raise. The point is, it is quite natural to declare a bridged network like this:

    network_name="mynet"

where mynet is a libvirt network on top of existing br0, like explained here:
https://libvirt.org/formatnetwork.html#examplesBridge

I tried to do it but got cryptic errors like:

      libvirt_domain.domain: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Unlike stated in the documentation, doing terraform apply was not enough to clear them.

I'm suggested this is made possible, as using a libvirt network is cleaner than directly hooking on the bridge.
It would also be more consistent with non-bridged setups.

**Comment by moio** [comment]
I have the feeling this boils down to the terraform-provider-libvirt, specifically this issue:

https://github.com/dmacvicar/terraform-provider-libvirt/issues/92

Can you confirm?

**Comment by MalloZup** [comment]
@moio, the fix was merged for plugin and tested, so now for this issue is only time to build the pkg and use the fix, which define the network as bridged mode

**Comment by Bischoff** [comment]
@MalloZup What is the current state? Do you think we can close this issue?

**Comment by moio** [comment]
@Bischoff hopefully the next terraform plugin upgrade will solve this.

**Comment by Bischoff** [comment]
@moio it's been a long time i have not tested such a setup, so i don't know myself if it works now. Let's close the issue, we can reopen it if not fixed by terraform plugin upgrades already.
